/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 la_night_city.glb -T
Author: FUD-UJEP (https://sketchfab.com/FUD-UJEP)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/la-night-city-a85450184c6e4ddf87b49c402641e5b4
Title: LA Night City
*/

import React, { useRef } from 'react'
import { useGLTF, PresentationControls, Float } from '@react-three/drei'

export function La_night_city(props) {
  const { nodes, materials } = useGLTF('/la_night_city-transformed.glb')
  return (
    <PresentationControls enabled={true}
    polar={[0, 0]}
    azimuth={[-0.25, 0.25]}>
    <Float 
    speed={.3} // Animation speed, defaults to 1
    rotationIntensity={.5} // XYZ rotation intensity, defaults to 1
    floatIntensity={.3} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
    floatingRange={[0, 0]}>

    <group position={[0.5, -1, 0.1  ]} rotation={[0, -0.5, 0]} scale={0.4} {...props} dispose={null}>
      <mesh geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0.geometry} material={materials.Dtla_Orbit_u3_v1} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={1.124} />
      <mesh geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0.geometry} material={materials.Dtla_Orbit_u1_v1} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={1.124} />
      <mesh geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0.geometry} material={materials.Dtla_Orbit_u2_v2} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={1.124} />
      <mesh geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0.geometry} material={materials.Dtla_Orbit_u2_v1} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={1.124} />
      <mesh geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0.geometry} material={materials.Dtla_Orbit_u1_v2} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={1.124} />
    </group>
    </Float>
    </PresentationControls>
  )
}

useGLTF.preload('/la_night_city-transformed.glb')
